build.gradle

This enables the integration tests to run.

Add internal-cluster-test plugin to build.gradle

---

build.gradle

I copied this approach from other plugin repos, for example [common-utils][1].
[1]: https://github.com/opensearch-project/common-utils/blob/7736e080f9b0a2f6f2d9ad3b4272090b281ea8fa/build.gradle#L43-L52

Add version info to build.gradle

---

build.gradle

Backport of https://github.com/opensearch-project/custom-codecs/pull/14 to `2.10`

[Backport] [2.10] Fix publication group and project Github coordinates (#14)

---

.github/workflows/publish-maven-snapshots.yml

Adds workflow to publish snapshots to maven. Tested locally:
```
[root@dcda507af0e2 snapshots]# tree org
org
`-- opensearch
`-- plugin
`-- custom-codecs
|-- 3.0.0.0-SNAPSHOT
|   |-- custom-codecs-3.0.0.0-20230908.172334-1.pom
|   |-- custom-codecs-3.0.0.0-20230908.172334-1.pom.md5
|   |-- custom-codecs-3.0.0.0-20230908.172334-1.pom.sha1
|   |-- custom-codecs-3.0.0.0-20230908.172334-1.pom.sha256
|   |-- custom-codecs-3.0.0.0-20230908.172334-1.pom.sha512
|   |-- custom-codecs-3.0.0.0-20230908.172334-1.zip
|   |-- custom-codecs-3.0.0.0-20230908.172334-1.zip.md5
|   |-- custom-codecs-3.0.0.0-20230908.172334-1.zip.sha1
|   |-- custom-codecs-3.0.0.0-20230908.172334-1.zip.sha256
|   |-- custom-codecs-3.0.0.0-20230908.172334-1.zip.sha512
|   |-- maven-metadata.xml
|   |-- maven-metadata.xml.md5
| …
```

Add workflow to publish snapshots to maven

---

build.gradle
settings.gradle

Fix plugin publication name
```
$ tree ~/.m2/repository/org/opensearch/plugin/opensearch-custom-codecs/
├── 3.0.0.0-SNAPSHOT
│   ├── maven-metadata-local.xml
│   ├── opensearch-custom-codecs-3.0.0.0-SNAPSHOT.jar
│   ├── opensearch-custom-codecs-3.0.0.0-SNAPSHOT-javadoc.jar
│   ├── opensearch-custom-codecs-3.0.0.0-SNAPSHOT.module
│   ├── opensearch-custom-codecs-3.0.0.0-SNAPSHOT.pom
│   ├── opensearch-custom-codecs-3.0.0.0-SNAPSHOT-sources.jar
│   └── opensearch-custom-codecs-3.0.0.0-SNAPSHOT.zip
└── maven-metadata-local.xml
```
```
$ tree build/local-staging-repo/org/opensearch/plugin/                                          
build/local-staging-repo/org/opensearch/plugin/ …
```

Fix plugin publication name

---

build.gradle
scripts/build.sh

Add local staging maven jars publishing and add custom build.sh
https://github.com/opensearch-project/opensearch-build/issues/3743
https://github.com/opensearch-project/opensearch-build/issues/3971

Add local staging maven jars publishing and add custom build.sh

---

build.gradle
settings.gradle

Resolve dependency issues between jar and zip maven publications
https://github.com/opensearch-project/opensearch-build/issues/3743
https://github.com/opensearch-project/custom-codecs/issues/38

Resolve dependency issues between jar and zip maven publications

---

src/integrationTest/java/org/opensearch/index/codec/rest/CreateIndexWithCodecIT.java

Add support of secure OpenSearch clusters in integration tests
Closes https://github.com/opensearch-project/custom-codecs/issues/49

Add support of secure OpenSearch clusters in integration tests

---

src/integrationTest/java/org/opensearch/index/codec/rest/CreateIndexWithCodecIT.java

Backport of https://github.com/opensearch-project/custom-codecs/pull/61 to `2.10`

[Backport] [2.10] Fix protocol detection from https system property (#61)

---

src/integrationTest/java/org/opensearch/index/codec/rest/CreateIndexWithCodecIT.java

Backport of https://github.com/opensearch-project/custom-codecs/pull/61 to `2.x`

[Backport] [2.x] Fix protocol detection from https system property (#61)

---

.github/CODEOWNERS
MAINTAINERS.md

@sarthakaggarwal97 has been invited to join custom-codecs as a maintainer and he has accepted!

Add Sarthak Aggarwal as a maintainer

---

.github/workflows/check.yml
build.gradle

Publish only ZIP artifacts since the plugin has no xxx-client counterpart
```
$ ./scripts/build.sh -s true -v 3.0.0
```
```
$ tree build/local-staging-repo/org/opensearch/
build/local-staging-repo/org/opensearch/
└── plugin
└── opensearch-custom-codecs
├── 3.0.0.0-SNAPSHOT
│   ├── maven-metadata.xml
│   ├── maven-metadata.xml.md5
│   ├── maven-metadata.xml.sha1
│   ├── maven-metadata.xml.sha256
│   ├── maven-metadata.xml.sha512
│   ├── opensearch-custom-codecs-3.0.0.0-20231004.151629-1.pom
│   ├── opensearch-custom-codecs-3.0.0.0-20231004.151629-1.pom.md5
│   ├── opensearch-custom-codecs-3.0.0.0-20231004.151629-1.pom.sha1
│   ├── opensearch-custom-codecs-3.0.0.0-20231004.151629-1.pom.sha256
│   ├── opensearch-custom-codecs-3.0.0.0-20231004.151629-1.pom.sha512
│   ├── …
```

Publish only ZIP artifacts since the plugin has no xxx-client counterpart

---

.github/workflows/check.yml

Onboard jenkins prod docker images to github actions
#75

Onboard jenkins prod docker images to github actions

---

.github/workflows/check.yml

Removed explicit -Druntime.java version specifier for Gradle check
Forwardport from https://github.com/opensearch-project/custom-codecs/pull/77

Removed explicit -Druntime.java version specifier for Gradle check

---

src/main/java/org/opensearch/index/codec/customcodecs/Lucene95CustomStoredFieldsFormat.java
src/test/java/org/opensearch/index/codec/customcodecs/Lucene95CustomStoredFieldsFormatTests.java

Enables accessors for custom compression modes.
#88 

Accessors for custom compression modes

---

src/main/java/org/opensearch/index/codec/customcodecs/ZstdCompressionMode.java
src/main/java/org/opensearch/index/codec/customcodecs/ZstdNoDictCompressionMode.java

Removes redundant array resizes in Zstd compression modes.
Improves performance by eliminating redundant array resizing.

Remove redundant array resizing in Zstd compression modes.

---

.github/workflows/check.yml

Switch to macos-13 runner for assemble github actions due to macos-latest is now arm64
N/A

 Switch to macos-13 runner for assemble github actions due to macos-latest is now arm64

---

.github/workflows/check.yml

Backport of https://github.com/opensearch-project/custom-codecs/pull/138 to `2.x`

[Backport] [2.x] Switch to macos-13 runner for assemble github actions due to macos-latest is now arm64 (#138)

---

.github/workflows/check.yml

Backport of https://github.com/opensearch-project/custom-codecs/pull/138 to `2.14`

[Backport] [2.14] Switch to macos-13 runner for assemble github actions due to macos-latest is now arm64 (#138)

---

src/main/plugin-metadata/plugin-security.policy

Remove org.opensearch.secure_sm.ThreadPermission from plugin manifest, this permission should not be granted
Followup on https://github.com/opensearch-project/custom-codecs/pull/122

Remove org.opensearch.secure_sm.ThreadPermission from plugin manifest, this permission should not be granted

---

.github/workflows/check.yml
.github/workflows/ci.yml
.github/workflows/publish-maven-snapshots.yml
build.gradle

Set JDK21 as the baseline for the 3.0 major version

---

.github/workflows/check.yml

See please https://github.com/opensearch-project/opensearch-ci/issues/436
_List any issues this PR will resolve, e.g. Closes [...]._ 

 Temp use of older nodejs version before moving to Almalinux8

---

src/integrationTest/java/org/opensearch/index/codec/rest/CreateIndexWithCodecIT.java
src/main/java/org/opensearch/index/codec/customcodecs/CustomCodecPlugin.java
src/main/java/org/opensearch/index/codec/customcodecs/CustomCodecService.java
src/main/java/org/opensearch/index/codec/customcodecs/QatDeflate99Codec.java
src/main/java/org/opensearch/index/codec/customcodecs/QatLz499Codec.java
src/main/java/org/opensearch/index/codec/customcodecs/QatZipperFactory.java
src/test/java/org/opensearch/index/codec/customcodecs/CustomCodecTests.java

Validates that we only load the QAT codecs if QAT library is loaded
#168

Validating QAT Hardware Support before QAT Codecs are available

---

src/integrationTest/java/org/opensearch/index/codec/rest/CreateIndexWithCodecIT.java
src/main/java/org/opensearch/index/codec/customcodecs/CustomCodecPlugin.java
src/main/java/org/opensearch/index/codec/customcodecs/CustomCodecService.java
src/main/java/org/opensearch/index/codec/customcodecs/QatDeflate99Codec.java
src/main/java/org/opensearch/index/codec/customcodecs/QatLz499Codec.java
src/main/java/org/opensearch/index/codec/customcodecs/QatZipperFactory.java
src/test/java/org/opensearch/index/codec/customcodecs/CustomCodecTests.java

[Backport 2.16] Validating QAT Hardware Support before QAT Codecs are available (#169)

---

src/integrationTest/java/org/opensearch/index/codec/rest/CreateIndexWithCodecIT.java
src/main/java/org/opensearch/index/codec/customcodecs/CustomCodecPlugin.java
src/main/java/org/opensearch/index/codec/customcodecs/CustomCodecService.java
src/main/java/org/opensearch/index/codec/customcodecs/QatDeflate99Codec.java
src/main/java/org/opensearch/index/codec/customcodecs/QatLz499Codec.java
src/main/java/org/opensearch/index/codec/customcodecs/QatZipperFactory.java
src/test/java/org/opensearch/index/codec/customcodecs/CustomCodecTests.java

[Backport 2.x] Validating QAT Hardware Support before QAT Codecs are available (#169)

---

build.gradle
bwc-test/build.gradle

Bump 2.x to 2.18.0 since 2.17.0 branch was cut already
N/A (part of the release)

Bump 2.x to 2.18.0 since 2.17.0 branch was cut already

---

release-notes/opensearch-custom-codecs.release-notes-2.17.1.0.md

Add 2.17.1 release notes
Part of https://github.com/opensearch-project/opensearch-build/issues/5046

Add 2.17.1 release notes

---

.github/workflows/check.yml
src/main/java/org/opensearch/index/codec/customcodecs/QatZipperFactory.java
src/main/plugin-metadata/plugin-security.policy

A customer reached out to inform us that they were unable to use `qat_deflate` and `qat_lz4`. Upon investigation, I discovered that `isQATAvailable()` was returning `false` due to a `java.security` permission fail in [here](https://github.com/opensearch-project/custom-codecs/blob/main/src/main/java/org/opensearch/index/codec/customcodecs/QatZipperFactory.java#L187). This behavior is unexpected, as my initial PR did not require it (as far as I can remember). 
This PR addresses the issue by adding the necessary permission to the `qat-java` codebase.
@sarthakaggarwal97
For more information on following Developer Certificate of Origin and signing off your commits, please check …

Wrap a call to QatZipper with AccessController.doPrivileged.

---

.github/actions/run-bwc-suite/action.yaml
bwc-test/src/test/java/org/opensearch/customcodecs/bwc/CustomCodecsBwcCompatibilityIT.java
release-notes/opensearch-custom-codecs.release-notes-2.19.0.0.md

Add release notes for 2.19.0 release
Part of https://github.com/opensearch-project/custom-codecs/issues/205

Add release notes for 2.19.0 release

---

build.gradle

Bumped up the ZSTD library to version 1.5.6-1. This version adds support for custom sequence producers, which makes it possible to add QAT-accelerated ZSTD, in addition to the existing `qat_deflate` and `qat_lz4`.

Bump ZTD lib version to 1.5.6-1.

---

build.gradle
src/main/plugin-metadata/plugin-security.policy

Fix build due to phasing off SecurityManager usage in favor of Java Agent
N/A

Fix build due to phasing off SecurityManager usage in favor of Java Agent

---

.github/workflows/publish-maven-snapshots.yml
build.gradle
bwc-test/build.gradle

Update the Maven Snapshots publish URL in accordance with the recent Sonatype migration. 
https://central.sonatype.org/publish/publish-portal-snapshots/
We have stored the `onepassword` token in this `OpenSearch` repo secrets and new credentials for Sonatypes username & password have been stored in `onepassword`.  These credentials will be exported as env variables which used by maven publish.
Part of a campaign from https://github.com/opensearch-project/opensearch-build/issues/5551
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/custom-codecs/blob/main/CONTRIBUTING.md#dev …

Update the maven snapshot publish endpoint and credential

---

build.gradle
src/main/java/org/opensearch/index/codec/customcodecs/CustomCodecService.java
src/main/java/org/opensearch/index/codec/customcodecs/Lucene101CustomCodec.java
src/main/java/org/opensearch/index/codec/customcodecs/Lucene101QatCodec.java
src/main/java/org/opensearch/index/codec/customcodecs/QatDeflate101Codec.java
src/main/java/org/opensearch/index/codec/customcodecs/QatLz4101Codec.java
src/main/java/org/opensearch/index/codec/customcodecs/QatZstd101Codec.java
src/main/java/org/opensearch/index/codec/customcodecs/Zstd101Codec.java
src/main/java/org/opensearch/index/codec/customcodecs/ZstdNoDict101Codec.java
src/test/java/org/opensearch/index/codec/customcodecs/CustomCodecTests.java

This PR adds support for composite indices with custom codecs.
We delegate to the `CompositeCodec` instead of always delegating to PerFieldMappingPostingFormatCodec based on whether mapper has Composite fields.
Resolves https://github.com/opensearch-project/custom-codecs/issues/209

Adding support for composite index

---

.github/workflows/check.yml
.github/workflows/delete-backport-branch.yml
gradle/wrapper/gradle-wrapper.properties

Bump gradle to 8.14, fix backport-deletion and support JDK24
Resolves #https://github.com/opensearch-project/custom-codecs/issues/265

Bump gradle to 8.14, fix backport-deletion and support JDK24
