opensearch-project/custom-codecs

- .github/workflows/check.yml
> Add gradle check workflow

- .github/workflows/add-untriaged.yml
> Add add-untriaged GitHub workflow

- .github/workflows/add-untriaged.yml
- .github/workflows/check.yml
- build.gradle
> Rebase 2.x to main

- .github/workflows/add-untriaged.yml
- .github/workflows/check.yml
- build.gradle
> Rebase 2.10 to main

- build.gradle
> Set 2.x to track OpenSearch 2.11

- build.gradle
> Set 2.10 to track OpenSearch 2.10

- .github/workflows/backport.yml
- .github/workflows/delete-backport-branch.yml
Add backport workflows. Secrets have been added to this repo.
closes https://github.com/opensearch-project/custom-codecs/issues/11
> Add backport workflows

- build.gradle
Fix publication group and project Github coordinates
N/A
> Fix publication group and project Github coordinates

- release-notes/opensearch-custom-codecs.release-notes-2.10.0.0.md
> Add 2.10.0 release notes

- build.gradle
Update description to follow conventions defined [here](1).
> Update description metadata

- build.gradle
- src/integrationTest/java/org/opensearch/index/codec/rest/CreateIndexWithCodecIT.java
Add integration test suite for the plugin so we could run distribution tests
See please https://github.com/opensearch-project/opensearch-build/issues/3971
> Add integration test suite for the plugin

- src/integrationTest/java/org/opensearch/index/codec/rest/CreateIndexWithCodecIT.java
Fix protocol detection from https system property
Closes https://github.com/opensearch-project/custom-codecs/issues/60
> Fix protocol detection from https system property

- .github/workflows/check.yml
Switch to ci-runner user for the checks
#75
https://github.com/opensearch-project/opensearch-build/pull/4200
> Switch to ci-runner user for the checks

- build.gradle
Bump version to 2.11.1 from 2.11.0
> Increment  version to 2.11.1

- build.gradle
See [template example here][1].
[1]: https://github.com/opensearch-project/opensearch-plugin-template-java/blob/3b805c245a3791003160dbd1a47762cc0d6cafc1/build.gradle#L117-L125
Resolved #84
> Add updateVersion gradle task from plugin template

- .github/actions/create-bwc-build/action.yaml
- .github/actions/run-bwc-suite/action.yaml
- .github/workflows/ci.yml
- bwc-test/build.gradle
- bwc-test/src/test/java/org/opensearch/customcodecs/bwc/CustomCodecsBwcCompatibilityIT.java
- bwc-test/src/test/java/org/opensearch/customcodecs/bwc/Song.java
Backport of https://github.com/opensearch-project/custom-codecs/pull/104 to `2.x`
> [Backport] [2.x] GA updates and minor BWC test cleanups (#104)

- release-notes/opensearch-custom-codecs.release-notes-2.12.0.0.md
> Version 2.12 Release Notes

- README.md
Add status badge for CI actions to README
Improves showing the current status of the repository CI actions.
> Add status badge for CI actions to README

- release-notes/opensearch-custom-codecs.release-notes-2.13.0.0.md
> Add 2.13 release notes

- release-notes/opensearch-custom-codecs.release-notes-2.13.0.0.md
Update opensearch-custom-codecs.release-notes-2.13.0.0.md to conform with OpenSearch guidelines
Closes https://github.com/opensearch-project/custom-codecs/issues/131
> Update opensearch-custom-codecs.release-notes-2.13.0.0.md to conform with OpenSearch guidelines

- build.gradle
> Bump 2.x to 2.15.0

- release-notes/opensearch-custom-codecs.release-notes-2.14.0.0.md
> Add release notes for 2.14

- release-notes/opensearch-custom-codecs.release-notes-2.15.0.0.md
Add 2.15.0 release notes
Part of https://github.com/opensearch-project/custom-codecs/issues/143
> Add 2.15.0 release notes

- release-notes/opensearch-custom-codecs.release-notes-2.16.0.0.md
OpenSearch Custom Codecs Release Notes for v2.16
https://github.com/opensearch-project/custom-codecs/issues/160
> Release Notes for v2.16

- release-notes/opensearch-custom-codecs.release-notes-2.17.0.0.md
Add 2.17.0 release notes
Part of https://github.com/opensearch-project/custom-codecs/issues/181
> Add 2.17.0 release notes

- release-notes/opensearch-custom-codecs.release-notes-2.17.1.0.md
(cherry picked from commit 1b15b01c2192f8f30f895d9790571468c403d13d)
Add 2.17.1 release notes (#193) (#194)
Part of https://github.com/opensearch-project/opensearch-build/issues/5046
> Add 2.17.1 release notes (#193) (#194)

- build.gradle
> Bump 2.x to 2.19.0

- release-notes/opensearch-custom-codecs.release-notes-2.18.0.0.md
Add 2.18.0 release notes
Part of https://github.com/opensearch-project/custom-codecs/issues/190
> Add 2.18.0 release notes

- .github/workflows/check.yml
Fix GitHib action workflows
N/A
> Fix GitHib action workflows

- .github/actions/run-bwc-suite/action.yaml
- release-notes/opensearch-custom-codecs.release-notes-2.19.0.0.md
Add release notes for 2.19.0 release
Part of https://github.com/opensearch-project/custom-codecs/issues/205
> Add release notes for 2.19.0 release

- build.gradle
Bump 2.x to 2.20
Part of https://github.com/opensearch-project/custom-codecs/issues/205
> Bump 2.x to 2.20

- release-notes/opensearch-custom-codecs.release-notes-3.0.0.0.md
Add release notes for 3.0 alpha release
Resolves #[Issue number to be closed when this PR is merged]
> Add release notes for 3.0 alpha release

- release-notes/opensearch-custom-codecs.release-notes-3.0.0.0-alpha1.md
- release-notes/opensearch-custom-codecs.release-notes-3.0.0.0.md
Add release note for 3.0 alpha1
> add release note for 3.0 alpha1

- release-notes/opensearch-custom-codecs.release-notes-3.0.0.0-beta1.md
Add release notes on version 3.0.0.0-beta1
> Add release notes on version 3.0.0.0-beta1

- release-notes/opensearch-custom-codecs.release-notes-3.0.0.0.md
Add 3.0.0 release notes for GA
Resolves #[Issue number to be closed when this PR is merged]
> Add 3.0.0 release notes for GA

- bwc-test/build.gradle
> Fix version on bwc test dependency

- .github/workflows/check.yml
- build.gradle
Add code coverage
Follow up on https://github.com/opensearch-project/custom-codecs/pull/267#issuecomment-3157212308
> Add code coverage
